api/urls.py
# api.urls

from django.conf.urls import url, include
from django.urls import path
from rest_framework import routers
from . import views

# TODO: too much of a black box
#router = routers.DefaultRouter()

#router.register(r'geoms', views.FeatureViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    #path('',include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    
    # 
    path('features/',views.LPViewSet.as_view({'get': 'list'})),
    
    # called from loadGeodata() in draw.html
    path('geoms/',views.FeatureViewSet.as_view({'get': 'list'}))

    #url(r'^', include(router.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

main/urls.py
from django.conf import settings
#from django.conf.urls.static import static
#from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path#, include
from django.views.generic.base import TemplateView

from . import views

app_name='main'
urlpatterns = [
    path(r'', login_required(TemplateView.as_view(
        template_name="main/draw.html")), name="draw"),
    path('<int:projid>/', views.DrawView.as_view(), name='draw'),
    path('fetch_projects/', views.fetchProjects, name='fetch-projects'),
    
    path('feature_create/', views.createFeature, name='feature-create'),
    path('feature_delete/', views.deleteFeature, name='feature-delete'),
    path('feature_update/', views.updateFeature, name='feature-update'),
    
    path('dl_project/<str:prj>/<str:format>', views.download_project, name="dl-project"), # 
    #path('dl_map/<int:id>/<str:format>', views.download_map, name="dl-map"), # 
    
]
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

whgdraw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from main import views
from api.views import MapNamesView

urlpatterns = [
    path(r'', TemplateView.as_view(template_name="main/index.html"), name="index"),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('draw/', include('main.urls')),
    
    path('project_create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project_delete/<int:id>', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('project_update/<int:pk>', views.ProjectUpdateView.as_view(), name='project-update'),
    
    path('project_download/<int:projid>', views.download_project, name='dl-project'),


    path('map_create/<int:pid>', views.MapCreateView.as_view(), name='map-create'),
    path('map_delete/<int:id>', views.MapDeleteView.as_view(), name='map-delete'),
    path('map_update/<int:pk>', views.MapUpdateView.as_view(), name='map-update'),    
    
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('names/', MapNamesView.as_view(), name='names-api'),
    
    
]
# + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)


#path('create_project/', views.ProjectCreateView.as_view(), name='project-create'),
#path('create_map/', views.MapCreateView.as_view(), name='map-create'),

#path('delete_project/', views.ProjectDeleteView.as_view(), name='project-delete'),
#path('delete_map/', views.MapDeleteView.as_view(), name='map-delete'),

main/forms.py
# main.forms

from django import forms
#from django.forms import ClearableFileInput
from .models import Project, Map
#from main.choices import FORMATS, DATATYPES, STATUS

# id, title, label, owner_id, create_date, uri
class ProjectCreateModelForm(forms.ModelForm):
    
    class Meta:
        model = Project
        fields = ('title','label','owner','uri')
        #widgets = {
            #'description': forms.Textarea(attrs={
              #'rows':2,'cols': 35,'class':'textarea','placeholder':'brief description'})
            #,'uri_base': forms.URLInput(attrs={
              #'placeholder':'Leave blank unless record IDs are URIs','size':35})
        #}

    def __init__(self, *args, **kwargs):
        super(ProjectCreateModelForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required':'The field {fieldname} is required'.format(
          fieldname=field.label)}    
            
class MapCreateModelForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ('owner','project','title','label', 'year_pub',
                  'cite_uri','cite_text', 'tiles', 'when', 'when_constant', 'minzoom', 'maxzoom', 'bounds')
        widgets = {
        'when': forms.Textarea(attrs={
          'rows':2,'cols': 35,'class':'textarea','placeholder':'json when object'})
        ,'cite_uri': forms.URLInput(attrs={
          'placeholder':'Permalink?','size':35})
    }


    def __init__(self, *args, **kwargs):
        super(MapCreateModelForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.error_messages = {'required':'The field {fieldname} is required'.format(
          fieldname=field.label)}    

main/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.gis.geos import GEOSGeometry
from django.http import JsonResponse, FileResponse
from django.db.models import Q
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import (View, CreateView, DeleteView, ListView, UpdateView)

import json, sys, time, datetime, csv, os
import reverse_geocoder as rg
from .utils import myprojects
from main.models import Project, Map, Feature, Name, ProjectUser, ProjectPlacetype
from main.forms import ProjectCreateModelForm, MapCreateModelForm

class DrawView(LoginRequiredMixin, View):
  #template_name = 'main/draw.html'

  def get(self, request, *args, **kwargs):
    context = {'projid': self.kwargs['projid']}
    return render(request, 'main/draw.html', context)

  # kwargs = {'projid':<n>}
  #def get_context_data(self, *args, **kwargs):
    #context = super(DrawView, self).get_context_data(*args, **kwargs)

    #context['projid'] = self.kwargs['projid']
    #return context


class DashboardView(LoginRequiredMixin, ListView):
  context_object_name = 'project_list'
  template_name = 'main/dashboard.html'

  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'

  def get_queryset(self):
    # TODO: make .team() a method on User
    me = self.request.user
    if me.username in ['admin','karlg']:
      print('in get_queryset() if',me)
      return Project.objects.all().order_by('label')
    else:
      # returns permitted datasets (rw) + black and dplace (ro)
      return Project.objects.filter( Q(id__in=myprojects(me)) | Q(owner=me) ).order_by('label')

  def get_context_data(self, *args, **kwargs):
    me = self.request.user
    context = super(DashboardView, self).get_context_data(*args, **kwargs)
    print('in get_context',me)

    #types_ok=['ccodes','copied','drawn']
    # list areas
    #userareas = Area.objects.all().filter(type__in=types_ok).order_by('created')
    #context['area_list'] = userareas if me.username == 'whgadmin' else userareas.filter(owner=self.request.user)

    #context['viewable'] = ['uploaded','inserted','reconciling','review_hits','reviewed','review_whg','indexed']
    # TODO: user place collections
    #print('DashboardView context:', context)
    return context

class ProjectCreateView(LoginRequiredMixin, CreateView):
  form_class = ProjectCreateModelForm
  template_name = 'main/project_create.html'
  success_message = 'project created'
  success_url="/home/dashboard/"

  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'

class ProjectUpdateView(LoginRequiredMixin, UpdateView):
  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'
  success_url="/home/dashboard/"

  #form_class = ProjectDetailModelForm
  template_name = 'main/project_update.html'
  model = Project
  fields = ['id', 'title', 'label', 'owner', 'uri']

  def get_context_data(self, *args, **kwargs):
    context = super(ProjectUpdateView, self).get_context_data(*args, **kwargs)
    print('ProjectUpdateView get_context_data() kwargs:',self.kwargs)
    id_ = self.kwargs.get("pk")
    proj = get_object_or_404(Project, id=id_)
    maps = Map.objects.all().filter(project=proj,tiles=True).order_by('label')

    context['maps'] = maps
    context['project_id'] = id_
    return context

class ProjectDeleteView(DeleteView):
  template_name = 'main/project_delete.html'

  def get_object(self):
    id_ = self.kwargs.get("id")
    return get_object_or_404(Project, id=id_)

  def get_success_url(self):
    return reverse('main:dashboard')


class MapCreateView(LoginRequiredMixin, CreateView):
  form_class = MapCreateModelForm
  template_name = 'main/map_create.html'
  success_message = 'map created'
  success_url="/home/dashboard/"

  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'


class MapDeleteView(DeleteView):
  template_name = 'main/map_delete.html'

  def get_object(self):
    id_ = self.kwargs.get("id")
    return get_object_or_404(Map, id=id_)

  def get_success_url(self):
    return reverse('home')

class MapUpdateView(LoginRequiredMixin, UpdateView):
  form_class = MapCreateModelForm
  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'
  #success_url='/home/project_update/'+str(proj_id)

  model = Map
  template_name = 'main/map_update.html'
  #fields = ['id', 'project', 'title', 'label', 'cite_text', 'cite_uri', 'tiles', 'when',
        #'when_constant','minzoom','maxzoom','bounds']

  def get_context_data(self, *args, **kwargs):
    context = super(MapUpdateView, self).get_context_data(*args, **kwargs)
    id_ = self.kwargs.get("pk")
    proj_id = get_object_or_404(Map,pk=id_).project_id

    context['map_id'] = id_
    context['project_id'] = proj_id
    return context

  def get_success_url(self, *args, **kwargs):
    proj_id=get_object_or_404(Map,pk=self.kwargs.get("pk")).project_id
    print('get_success_url; proj_id',proj_id)        
    return '/project_update/'+str(proj_id)

@login_required
def fetchProjects(request):
  u=request.user
  result = {"projects":[], "maps":[]}
  if u.is_superuser:
    projects = Project.objects.all()
  else:
    collab_projects = ProjectUser.objects.filter(user=u).values_list('project',flat=True)
    projects = Project.objects.filter( Q(id__in=collab_projects) | Q(owner=u) )
  #maps = Map.objects.filter(tiles=True)
  maps = Map.objects.filter(tiles=True,project__in=projects).order_by('label')
  #feature_count = sum([m.features.count() for m in maps])
  for p in projects:
    count=sum([m.features.count() for m in p.maps.all()])
    ppt=ProjectPlacetype.objects.filter(project=p)
    placetypes=[ t.as_dict() for t in ppt ]
    result['projects'].append(
          {'id':p.id, 'owner':p.owner_id, 'label':p.label, 'title':p.title
             ,'feature_count':count, 'placetypes': placetypes}
        )
  for m in maps:
    result['maps'].append(
          {'id':m.id, 'proj_id':m.project_id, 'proj_label':m.project.label, 'label':m.label, 
             'title':m.title, 'cite_uri':m.cite_uri, 'cite_text':m.cite_text, 
             'minzoom':m.minzoom, 'maxzoom':m.maxzoom, 'bounds':m.bounds,
             'when':m.when, 'when_constant':m.when_constant,'feature_count':m.features.count()}
        )

  return JsonResponse(result,safe=False)

@login_required    
def deleteFeature(request,*args,**kwargs):
  print('deleteFeature() request', request.POST)
  print('in deleteFeature() kwargs', kwargs)
  if request.method == 'POST':
    _id = int(request.POST.get('lid'))
    print('_id',_id)
    try:
      #get_object_or_404(Feature, jsonb__properties__leaflet_id = _id).delete()
      get_object_or_404(Feature, jsonb__properties__leaflet_id__in=[int(_id),str(_id)]).delete()
      result = {"msg":"deleted "+str(_id)}
    except:
      result = {"msg":"delete of "+str(_id)+' failed: '+str(sys.exc_info())}
      print('delete failed',_id, sys.exc_info())
  return JsonResponse(result,safe=False)

@login_required    
def updateFeature(request):
  newfeat = json.loads(request.POST['jsonb'])
  print('newfeat in updateFeature(), type', newfeat,type(newfeat))
  _id = newfeat['fid']
  leaflet_id = newfeat['properties']['leaflet_id']
  name = newfeat['properties']['names'][0]['toponym']; print('name', name)
  placetype = newfeat['properties']['types'][0]['identifier']; print('placetype',placetype)
  # get existing 
  #fobj = Feature.objects.filter(pk=_id)
  fobj = Feature.objects.filter(jsonb__properties__leaflet_id = leaflet_id)
  ftype = newfeat['geometry']['type']; print('ftype',ftype) # Point, LineString, etc
  geowkt = GEOSGeometry(json.dumps(newfeat['geometry']))
  # replace some values
  try:
    fobj.update(title = name)
    fobj.update(placetype = placetype)
    fobj.update(jsonb = newfeat)
    fobj.update(geom_point = geowkt if ftype == 'Point' else None)
    fobj.update(geom_line = geowkt if ftype == 'LineString' else None)
    fobj.update(geom_poly = geowkt if ftype == 'Polygon' else None)
    result = {"msg":"updated "+json.dumps(newfeat)}    
  except:
    result = {"msg":"updating "+str(_id)+' failed; '+sys.exc_info()}
    #result = {"msg":"updating failed"+sys.exc_info()}
  return JsonResponse(result,safe=False)

@login_required    
def createFeature(request):
  print('in createFeature()', request.POST)
  mapid = int(request.POST['mapid'])
  nameid = int(request.POST['nameid'])
  print('mapid',mapid,type(mapid))
  if mapid > 0:
    feature = json.loads(request.POST['jsonb'])
    names = feature['properties']['names']
    types = feature['properties']['types']
    ftype = feature['geometry']['type']
    mapobj = get_object_or_404(Map, pk=int(mapid))
    nameobj = get_object_or_404(Name, pk=int(nameid))
    print('nameobj',nameobj)
    newfeat = Feature(
          user = request.user,
            title = names[0]['toponym'],
            src_name = nameobj,
            placetype = types[0]['identifier'],
            jsonb = feature,
            map = mapobj,
            geom_point = GEOSGeometry(json.dumps(feature['geometry'])) if ftype == 'Point' else None,
            geom_line = GEOSGeometry(json.dumps(feature['geometry'])) if ftype == 'LineString' else None,
            geom_poly = GEOSGeometry(json.dumps(feature['geometry'])) if ftype == 'Polygon' else None,
        )
    newfeat.save()
    print('feat',newfeat)
    result = {"mapid": mapid, "ftype": ftype, "name": names[0], "errors":[]}
  else:
    # no map selected
    result = {"errors":["no map selected"]}
  return JsonResponse(result,safe=False)

def get_minmax(when):
  tsarr=when['timespans']
  starts=[];ends=[];years=[];nullset=set([None]);
  for ts in tsarr:
    years.append(int(list(ts['start'].values())[0]))
    years.append(int(list(ts['end'].values())[0]) if 'end' in ts.keys() else None)
    years = list(set(years)-nullset)

main/templates/main/base.html
{% load i18n static %}
<!DOCTYPE html>
{% load fontawesome_5 %}
<html lang="en">
<head>
  {% fontawesome_5_static %}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-147954240-1"></script> -->
  <!-- <script>
	window.dataLayer = window.dataLayer || [];
	function gtag(){dataLayer.push(arguments);}
	gtag('js', new Date());

	gtag('config', 'UA-147954240-1');
  </script> -->

  {% block title %}<title>linkedplaces.draw</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- JQuery -->
  <script
	  src="https://code.jquery.com/jquery-3.3.1.min.js"
	  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
	  crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.css">
  <!-- Bootstrap -->
  <script src="https://unpkg.com/popper.js/dist/umd/popper.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <!-- Add additional CSS in static -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/> 
  <link href="https://fonts.googleapis.com/css?family=EB+Garamond|Raleway&display=swap" rel="stylesheet">
  <!-- some pages will want more -->
  {% block extra_head %}{% endblock %}
</head>
<body>
  <header>
    <!--<nav class="navbar navbar-expand-lg navbar-light">-->
    <nav class="navbar navbar-expand navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'main:draw' %}">linkedplaces.draw</a>
		  <div class="small">
        <span id="beta_badge" class="badge badge-warning mr-2">ALPHA 0.1</span>
      </div>
        <div class="collapse navbar-collapse pt-1" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto pt-2">
			{% if user.is_authenticated %}
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
			  </li>
			  <li class="nav-item larger">
				<a class="nav-link" rel="tooltip" title="{{ user }} settings"
				href="{% url 'profile' %}">{{ user }} {% fa5_icon 'user' 'fas' %}</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link `ml-5" href="javascript:{document.getElementById('logout').submit()}">Logout</a>
				<form id="logout" method="post" action="{% url 'logout' %}">
				  {% csrf_token %}</form>
			  </li>
            {% else %}
			  <li class="nav-item">
				<a class="nav-link ml-5" href="{% url 'register' %}">Register</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'login' %}">Login</a>
			  </li>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  {% block content %}
  <div class="container" id="content">content</div>
  {% endblock %}


</body>
</html>

main/templates/main/dashboard.html
<!-- main/home.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load fontawesome_5 %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
{% endblock %}
{% block content %}
<div class="container">
    <div id="dataset_list" class="mt-3">
      <!--{# if messages %}-->
      <!--<p>{# for message in messages %}{ message }}{# endfor %}</p>-->
      <!--{# endif %}-->
      <h4 class="mt-3">Projects
        {{ referrer }}<small class="half"><a href="{% url 'project-create' %}" class="ml-5">
          {% fa5_icon 'plus' 'fas' %} add new</a></small>
      </h4>
      <div class="list-box">
        <!-- id, title, label, owner_id, create_date, uri-->
        <table class="table table-striped">
          <thead class="small">
            <th></th>
            <th>id</th>
            <th>title</th>
            <th>label</th>
            <th>created (utc)</th>
            <th>url</th>
            <th>owner</th>
          </thead>
          <tbody>
            {% for p in project_list %}
              <tr class="project-row">
                <td><a href="{% url 'project-delete' p.id %}">{% fa5_icon 'trash-alt' 'fas' %}</a></td>
                <td>{{ p.id }}</td>
                <td><a href="{% url 'project-update' p.id %}" title="Update project" rel="tooltip"
                  > {{ p.title }} </a></td>
                <td>{{ p.label }}</td>
                <td class="small">{{ p.create_date|date:"d M Y, H:i" }}</td>
                <td>{{ p.uri }}</span></td>
                <td>{{ p.owner_id }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
</div> <!-- container -->  
<script type="text/javascript">

</script>
{% endblock %}

main/templates/main/index.html
<!-- main/home.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
<style>
.ui-autocomplete {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  list-style: none;
  font-size: 14px;
  text-align: left;
  background-color: #ffffff;
  border: 1px solid #cccccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  background-clip: padding-box;
}

.ui-autocomplete > li > div {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333333;
  white-space: nowrap;
}

.ui-state-hover,
.ui-state-active,
.ui-state-focus {
  text-decoration: none;
  color: #262626;
  background-color: #f5f5f5;
  cursor: pointer;
}

.ui-helper-hidden-accessible {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
</style>
{% endblock %}
{% block content %}
<div class="container">
  <div class="pt-3">
    <p>A tool for digitizing features found on historical maps and maps of history</p>
    <p><a href="{% url 'main:draw' %}">Begin...</a></p>
  </div>
  <!--<h1>jQuery UI Autocomplete with Bootstrap Styling</h1>-->
  <!--<form>-->
    <!--<div class="form-group">-->
      <!--<label for="tags">Tags</label>-->
      <!--<input type="text" class="form-control" id="tags">-->
    <!--</div>-->
  <!--</form>  -->
</div>
<script type="text/javascript">
<!--$(function() {-->
  <!--var availableTags = [-->
    <!--"ActionScript",-->
    <!--"AppleScript",-->
    <!--"Asp",-->
    <!--"BASIC",-->
    <!--"C",-->
    <!--"C++",-->
    <!--"Clojure",-->
    <!--"COBOL",-->
    <!--"ColdFusion",-->
    <!--"Erlang",-->
    <!--"Fortran",-->
    <!--"Groovy",-->
    <!--"Haskell",-->
    <!--"Java",-->
    <!--"JavaScript",-->
    <!--"Lisp",-->
    <!--"Perl",-->
    <!--"PHP",-->
    <!--"Python",-->
    <!--"Ruby",-->
    <!--"Scala",-->
    <!--"Scheme"-->
  <!--];-->
  <!--$("#tags").autocomplete({-->
    <!--source: availableTags-->
  <!--});-->
});
</script>
{% endblock %}

main/templates/main/map_create.html
<!-- main/map_create.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load fontawesome_5 %}
{% block title %}<title>lp.draw::create map</title>{% endblock %}

{% block content %}
<div class="container mt-2">
    <div id="content">
    <h4 class="text-warning">create map</h4>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    </div>
</div>
{% endblock %}

main/templates/main/map_delete.html
<!-- main/project.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
{% endblock %}
{% block content %}
<div class="container">
  <div class="pt-3">
    <h4 class="text-warning">delete map</h4>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>  
  </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}

main/templates/main/map_update.html
<!-- main/project.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
{% endblock %}
{% block content %}
<div class="container">
  <div class="pt-3">
    <h4 class="text-warning">update map</h4>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
  </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}

main/templates/main/project_create.html
<!-- main/project_create.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load fontawesome_5 %}
{% block title %}<title>lp.draw::create project</title>{% endblock %}

{% block content %}
<div class="container mt-2">
    <div id="content">
    <h4 class="text-warning">create project</h4>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>    
    </div>
</div>
{% endblock %}

main/templates/main/project_delete.html
<!-- main/project.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
{% endblock %}
{% block content %}
<div class="container">
  <div class="pt-3">
    <h4 class="text-warning">delete project</h4>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>  
  </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}

main/templates/main/project_update.html
<!-- main/project.html -->
{% extends "main/base.html" %}
{% load leaflet_tags %}
{% load fontawesome_5 %}
{% load static %}
{% block title %}<title>whg.draw</title>{% endblock %}
{% block extra_head %}
{% endblock %}
{% block content %}
<div class="container">
  <h4 class="text-warning mt-3">project detail</h4>
  {{ context }}
  <div class="row">
    <div class="pt-3 col-sm-6">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Update">
          <span class="ml-2"><a href="javascript:history.back()">Cancel</a></span>
      </form>
    </div>
    <div class="col-sm-6">
    <h5>Maps <small><a href="{% url 'map-create' project_id %}" class="ml-5">
          {% fa5_icon 'plus' 'fas' %} add new</a></small></h5>
    <ul>
      {% for m in maps %}
        <li><a href="{% url 'map-update' m.id %}">{{m.title}}</a> ({{m.label}})</li>
      {% endfor %}
    </ul>
    <div>
  </div>
</div>
<script type="text/javascript">

</script>
{% endblock %}